# Generated by Django 4.2.7 on 2024-10-02 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=13, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('statement', models.CharField(max_length=2500)),
                ('explanation', models.CharField(max_length=2500)),
                ('score', models.PositiveIntegerField()),
                ('axis_type', models.CharField(choices=[('Numeros', 'Números'), ('Geometria', 'Geometría'), ('Álgebra y Funciones', 'Álgebra y funciones'), ('Probabilidad y estadística', 'Probabilidad y estadística')], max_length=50)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.test')),
            ],
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='interview.question')),
            ],
        ),
    ]
