# Generated by Django 4.2.7 on 2024-10-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_studenttest_alter_answer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
